config/routes.rb
Rails.application.routes.draw do

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    Task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :importance)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :importance %>
  <%= f.number_field :importance %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>****** To do List ******</h1>

<%= link_to "Add a new task", new_task_path %>

<% @tasks.each do |task| %>
<h2><%= task.name %></h2>
<p><%= task.description %></p>
<p><%= task.importance %></p>
<%= link_to "View details", task_path(task) %>
<%= link_to "Delete", task_path(task), method: :delete %>

<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :importance %>
  <%= f.number_field :importance %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>****** <%= @task.name %> ******</h1>

<p><%= @task.description %></p>
<p><%= @task.importance %></p>

<%= link_to "Back to the full list", tasks_path %>